### ISSUE TITLE
Choose LDAP library

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#1]
We should use a library for accessing / modifying the LDAP tree.

Options:
1. https://github.com/adLDAP/adLDAP - "old"
2. https://github.com/adLDAP2/adLDAP2 - new version of adLDAP, work in progress, PHP 5.4+
3. https://github.com/chanmix51/SlapOM - maps LDAP entities to PHP objects in a smart way, not much known usage in the wild
4. https://github.com/ldaptools/ldaptools - nice syntax, lots of sugar for querying and accessing data but PHP 5.6 (!)
5. ...?

**Comment by faboschert** [comment]
My first impression of the libraries you mentioned:
1. adLDAP: provides basic functions to manage a LDAP tree containing groups and users. Nevertheless it seems to have everything we need.
2. adLDAP2: basically like adLDAP, but with a few functions added, but the documentation is incomplete yet.
3. SlapOM: I couldn't find a documentation for SlapOM. We'd need to read the code to use this library.
4. ldaptools: compared to adLDAP it is more centered on LDAP-objects. It is not split into categories like users or groups, but uses objects for everything.
5. Apart from the 4 libraries there are a lot more out there: https://packagist.org/search/?q=ldap
The list contains the LDAP-libraries of, among others, Laravel and Drupal.

**Comment by leomelzer** [comment]
After having a second look, I cast my vote for adLDAP2 as adLDAP1 will probably be discontinued at some point and the others have the flaws you just mentioned.
I think the documentation is "good enough" at this point, especially the Wiki pages seem up to date, e.g. https://github.com/Adldap2/Adldap2/blob/master/docs/GETTING-STARTED.md

We will most likely only deal with the "user" and "group" objects anyways, a subset of the supported objects. 

So: +1 for adLDAP2

Which modules from Packagist would you include in our considerations? https://github.com/XavRsl/Ldap look nice but can only read (no update) from LDAP so far.

**Comment by faboschert** [comment]
I have to admit that I couldn't find a library on the Packagist website yet which serves our needs. Some look promising but then they are lacking a good documentation or functionality for user/group management.
I prefer adldap(2), too. Maybe we could help them with their documentation en passant ;)
Adldap2 seems to just be an alias for adLDAP v5.0.0 so we could use the adLDAP doc as well. (see https://github.com/Adldap2/Adldap2/issues/3 )

**Comment by leomelzer** [comment]
Cool, then we got it settled, adldap2 it is :)

**Comment by leomelzer** [comment]
I changed this yet again, Adldap2 apparently works nicely with **Active Directory** setups, but as we are using OpenLDAP, this wasn't really working for us. I tried a while to work around the issues but eventually gave up.

We're now using the equally nice Zend\Ldap library, see http://framework.zend.com/manual/current/en/modules/zend.ldap.api.html

As for passwords in LDAP, I found this interesting link: http://www.openldap.org/faq/data/cache/347.html
