### ISSUE TITLE
Unicode Icons vs. something else?

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#20]
The unicode icons on the manage account page unfortunately don't work 100% for me (OS X, Firefox): 
![screenshot 2015-07-02 10 21 48](https://cloud.githubusercontent.com/assets/23313/8472933/953d869a-20a5-11e5-9563-e49ac01c0817.png)
The pen icon for the edit button works again. We could leave it like this or incorporate something like [fontawesome](https://fortawesome.github.io/Font-Awesome/) or [icono.css](https://saeedalipoor.github.io/icono/)

What do you think @faboschert ?

**Comment by faboschert** [comment]
I also ran into this problem at first, although my two systems I used for the rendering are both running Linux and Firefox.
While I really like the unicode symbols I guess it would be better to use an icon font (Aside from that you can also use image sprites, but I think icon fonts are better for us, see http://www.jontetzlaff.com/blog/2013/04/29/image-sprites-vs-web-icon-fonts/).
There are loads of icon sets (http://weloveiconfonts.com/, http://fontello.com/, http://t3n.de/news/10-kostenlose-icon-fonts-450651/) and we also could create our own (https://icomoon.io); it depends on our flavor.

**Comment by leomelzer** [comment]
OK, good resources. Fontello.com is really cool!
So we could just include a subset of Fontawesome (we don't need them all...or maybe use [Web Symbols](http://www.justbenice.ru/studio/websymbols) (says SIL License on Fontello.com, but no mention of license on website itself). What do you think?

**Comment by faboschert** [comment]
@leomelzer Hmm, I think that I like font awesome a bit more. The user icon looks "friendlier" to me and they have e.g. a info-circle for info messages, a user-times for deleting users and a key for the password.

**Comment by leomelzer** [comment]
True. OK, so let's select a subset of FontAwesome on fontello.com and use it. I don't think we need them all...can you select the relevant ones and embed them? You can commit the config.xml (?) file that comes with the download as well, so we can extend the set when needed. @faboschert
