### ISSUE TITLE
Use a more lightweight password strength estimator

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#28]
Use a smaller javascript for valuating the password strength or load the script dynamically.

**Comment by leomelzer** [comment]
Relevant discussion: https://github.com/studieren-ohne-grenzen/dashboard/commit/bb6d6873a82e02c38847070094fcc16c0aefcb6f#commitcomment-11992901

**Comment by leomelzer** [comment]
Password strength indicator should also be embedded in `/password/reset/{token}` page.
