### ISSUE TITLE
Confirm the email address

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#29]
by
a) adding a field to repeat the address
b) sending a test email
c) sending an email containing a confirmation link/code

**Comment by leomelzer** [comment]
Option c (probably) requires some sort of persistence on our end, like a SQL database. Not a problem itself, but something worth noting. This may also apply to a possible "reset password" feature which would require storing some kind of token again.

**Comment by faboschert** [comment]
Possible workaround without database: Use the encrypted email address as code. That should be enough for a confirmation. Anyway the solution with a database would be better of course.

**Comment by leomelzer** [comment]
Yeah, but confirmations (or password reset links, to think of the other issue this would apply to) should expire at some point, but as a basic version that would to. I guess soon - depending on #27 :) - we will need some kind of database anyways, we could as well use it for that. Thanks to the integration of Doctrine into Silex that wouldn't be a big issue I believe. We could start with `pdo_sqlite`.

**Comment by leomelzer** [comment]
Tokens can now be generated through `$app['random'](10)` where 10 is the number of characters the token will have (defaults to 8)

**Comment by faboschert** [comment]
Closing this, due to #39
