### ISSUE TITLE
Setup base application

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#3]
With Silex, as just decided.
- [x] Basic Silex app
- [x] Build management with Brunch
- [x] Dependency management with NPM/Bower/Composer
- [x] Migrate Prototyp to new app
- [x] Figure out how to secure the member area
- [x] Where/how to store LDAP settings

**Comment by leomelzer** [comment]
@faboschert I just pushed a basic setup to the `develop` branch. I'll figure out the basic LDAP authentication and config management (LDAP settings) and then we can move on and coordinate. You can try setting up the application on your system, hope there aren't any issues. Let me know if you run into any.

**Comment by leomelzer** [comment]
Also see the README.md file, I tried to explain all the different folders etc.

**Comment by faboschert** [comment]
Nice job! It works without a problem.
In regard to the authentication management we might have a look at [warmans/silex-ldap-auth-controller-provider](https://github.com/warmans/silex-ldap-auth-controller-provider), which uses the Zend\Ldap library, to get an idea of the basic structure we'll have to use.
Further there are code snippets for the Silex [SecurityServiceProvider](http://silex.sensiolabs.org/doc/providers/security.html) and for the [LDAP authentication](http://adldap.sourceforge.net/wiki/doku.php?id=documentation_examples#authenticating_a_user).

**Comment by leomelzer** [comment]
Awesome, good to hear. Yeah, I liked that as well. Also https://github.com/DerManoMann/ldap-auth-service-provider may be interesting (also uses Zend LDAP). We'll want to expose the adldap instance to the whole application, too, so we're able to use it for the different features.

**Comment by leomelzer** [comment]
- Configuration is in file `app.config.php`, see the sample file on how to set it up. 
- Basic LDAP based authentication (and access to the LDAP resource for our other operations) is now available
