### ISSUE TITLE
Let the client memorize the filter settings

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#30]
The search term and the applied filters shouldn't be reset, when the site is reloaded after the http POST request.

**Comment by leomelzer** [comment]
I think this could be solved two ways
- directly in the frontend by using `localStorage` or a cookie through Javascript
- in the backend by using the `SessionServiceProvider` like `$app['session']->set('filter', $value);` and reading the same with twig in the template

**Comment by leomelzer** [comment]
...or by employing XHR to asynchronously posting actions and loading new content, see https://github.com/studieren-ohne-grenzen/dashboard/tree/feature-ajax-actions

**Comment by leomelzer** [comment]
Closed in favor of #69 - solves the same use case.
