### ISSUE TITLE
Feature: Reset password

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#33]
The user should be able to reset his/her own password. This should follow the standard protocol, in particular:
1. Request email address from user
2. Check if it exists
3. Present error and alternative way to contact IT (?)
4. Send email with special link to reset password to given email

When accessing such a reset link:
1. Check if the request was made within a certain time period
2. Present two input fields to set a new password for the user
3. Set an email to the user to confirm the password change, mention to contact IT if the action was not initiated by the user him/herself [?]

Not sure we find an off-the-shelf component for this particular feature.

**Comment by leomelzer** [comment]
Relevant:
- Twig Mail Template: https://github.com/jasongrimes/silex-simpleuser/blob/master/src/SimpleUser/Mailer.php#L193-L218
- Twig Mail Template: https://github.com/jasongrimes/silex-simpleuser/blob/master/src/SimpleUser/views/email/reset-password.twig
- Tokens / possible Implementation: https://github.com/jasongrimes/silex-simpleuser/blob/master/src/SimpleUser/UserController.php

**Comment by leomelzer** [comment]
@faboschert I started the implementation of this feature, see #41

A few notes:
1. `doctrine/dbal` is used to interface with a sqlite database
2. requests are currently valid for 1 week
3. quite a few TODOs left in the code [free for anyone to take on, help appreciated!]
4. changing the password (without knowing the old one) requires new privileges for our dashboard LDAP user, something we wanted to avoid but I see no way around it now
5. do we (yet) require the alternative email to be unique? That sounds like a useful constraint which might need implementation in #31

**Comment by leomelzer** [comment]
@faboschert Would you start the reset-process with
1. the user providing the UID?
2. the user providing the alternative mail address?

The first option is nice, because maybe the user doesn't remember the stored alternative mail. On the other hand only by providing the exact address the user knows where to look for the recovery mail. We can't simply print the stored address on request. 

I tend towards the first option. 

Other popular services use the mail address directly, but then it also serves as the UID directly.

**Comment by leomelzer** [comment]
As we just discussed: we prefer using the alternative mail address.

**Comment by leomelzer** [comment]
Just closed the relevant PR #41

**Comment by faboschert** [comment]
Great work!
Just want to note down two things for improvement:
- check for password security like this: https://github.com/studieren-ohne-grenzen/dashboard/blob/develop/public/index.php#L30
- give another error message, when the password validation went wrong and avoid the redirection to the login page in this case

**Comment by leomelzer** [comment]
Thanks for the suggestions, see 049ffd4a5ee97c097737886b2dc4f42d554d77b7
