### ISSUE TITLE
Request group membership

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#38]
Something like an add button and a selection box on the page for account management.

**Comment by leomelzer** [comment]
Cooll! You can call the appropriate methods in the LDAP adapter now: https://github.com/studieren-ohne-grenzen/dashboard/blob/api/app/sog/Dashboard/LdapAdapter.php#L284-L299

We still need the `pending` attributes in the LDAP tree, but this shouldn't prevent us from further implementation of this feature.

**Comment by leomelzer** [comment]
This feature is only missing the relevant UI, but is functional.

**Comment by faboschert** [comment]
Implemented along with the options to quit memberships and to drop the own requests. A dedicated page for managing one's group memberships was added for this.
