### ISSUE TITLE
Handle alternative mail

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#39]
@sebastian-leidig @kehrwoche We don't handle the mail-alternative through LDAP any longer. Instead we're creating sieve rules for dovecot directly, they can then be modified by members through Roundcube. Is that correct?

For reference: https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/lib/Roundcube/rcube_sieve.php

**Comment by sleidig** [comment]
correct, email copy/forwarding is configured by the users through roundcube-sieve

**Comment by leomelzer** [comment]
OK cool. So do we just list this in the FAQ (with link) or do we want/need any functionality for this feature in the dashboard?

**Comment by sleidig** [comment]
I would just put this into the documentation somewhere. No need to reimplement existing functionality.

**Comment by leomelzer** [comment]
@sebastian-leidig 
OK, just one final check:
1. User signs up with email foo@gmail.com
2. User is assigned foo@studieren-ohne-grenzen.org
3. In LDAP mail = foo@studieren-ohne-grenzen.org is stored
4. User receives one email at foo@gmail.com with details about account + password
5. System forgets foo@gmail.com
6. User has to setup forwarding etc manually if he wants to. All further mails are forwarded to foo@studieren-ohne-grenzen.org

Is that how we'll deal with it?

**Comment by sleidig** [comment]
(5.) foo@gmail.com is automatically kept in CiviCRM record
(6.) Do we add foo@studieren-ohne-grenzen.org to the mailinglists or rather the signup email foo@gmail.com? 
If indeed foo@studieren-ohne-grenzen.org is used for everything, I would vote for a forwarding rule to foo@gmail.com on signup.

**Comment by leomelzer** [comment]
I'd think it would be sensible to add foo@studieren-ohne-grenzen.org to the mailing lists. 

How do we do password resets in the dashboard then? I just realized that's the other (only?) time we would need a secondary email address on file.

**Comment by sleidig** [comment]
For that case we should maybe assign foo@gmail.com to an additional ldap field.
We can't rely on a user to keep the forwarding rule even if we add it in the beginning.

**Comment by faboschert** [comment]
Adding a ldap field for this would probably be the safest solution, I guess. Especially when thinking about the vision of all user data being stored in the ldap tree.
Forwarding the mails via roundcube leads to the problem that the email address will be stored in at least two places, which might confuse the users. Maybe we'll be able to directly read the forwarding options from ldap in the future (not necessarily with the aid of roundcube/sieve).

**Comment by leomelzer** [comment]
Hm...I'm thinking about our two typical use cases:
1. Light users, e.g. only participating from time to time, don't want to access two different mail accounts, like the forwarding to their university/regular mail address
2. Heavy users, e.g. coordinating a group or in a managing committee, want a separate dedicated mail account, prefer checking this

Use case 1 would prefer having us automatically setup the forwarding to the given email, they can optionally make use of the `@studieren-ohne-grenzen.org` address via Webmail etc. 

Use case 2 would like to remove the automatic forwarding, which is easy enough in Roundcube itself and can be described in the documentation (as @faboschert already did). This group probably doesn't mind spending a minute to change the behavior. 

As `|group 1| > |group 2|` we should probably automatically setup the forwarding with managesieve.

The script could look like this ("Alle weiterleiten" is the displayed name in Roundcube webmail):

```
equire ["copy"];
# rule:[Alle weiterleiten]
if true
{
    redirect :copy "leonhard.melzer@gmail.com";
}
```

Where to store the original email address with which the user registered? As it already is in CiviCRM we could request the address for the reset feature from there (through the CiviCRM API). Or we could revert the removal of the email field and keep it in LDAP (with the user being able to change it in the Dashboard) and state that this email is only used for the password reset. 

Hm...
@kehrwoche: what do you think?

**Comment by leomelzer** [comment]
Just realized Net_Sieve will not be continued: https://pear.php.net/bugs/bug.php?id=20552
Managesieve for Horde is the official successor: https://github.com/horde/horde/tree/master/framework/ManageSieve [but doesn't have an official package yet and is still alpha software]

**Comment by sleidig** [comment]
actually we are using managesieve currently.

There is a script to add the existing forwarding rules during migration. Have a look at /home/sebastian/mail_migration/create_sieve_forwardings.sh to see the rule and file location (although @leomelzer got the rule right)

**Comment by leomelzer** [comment]
Cool, I see. So we could / should create the same rule for new signups through PHP, right?

**Comment by leomelzer** [comment]
@sebastian-leidig @kehrwoche @faboschert Did we further decide on how to deal with this?

**Comment by sleidig** [comment]
Let me summarize again:
1. User signs up with email foo@gmail.com
2. User is assigned foo@studieren-ohne-grenzen.org
3. In LDAP mail = foo@studieren-ohne-grenzen.org is stored
4. In LDAP mail-alternative = foo@gmail.com is stored
5. User receives one email at foo@gmail.com with details about account + password
6. All further emails are sent to foo@studieren-ohne-grenzen.org
7. sieve rule is created by the system on signup, so all mail to foo@studieren-ohne-grenzen.org is automatically forwarded to foo@gmail.com
8. If desired, the user can manually deactivate/change the forwarding through Roundcube/manage-sieve

There now is an LDAP custom field "mail-alternative" to keep the original address. The only problem could be that Civi and LDAP data are not synced, so changing that private mail-id would involve two user actions?

And new users may tried to write to the mailinglists from foo@gmail.com, which would fail. (Although there may be a possibility to modify the Mailman-LDAP link to accept these)

**Comment by leomelzer** [comment]
Thanks for the summary, that sounds reasonable.

@faboschert we will need to take care of 7 then somehow (cronjob vs. interfacing with managesieve directly?). What do you think is a good solution?

@sebastian-leidig Your last point could be a concern, because simply hitting reply in the mail client will not allow the member to post the mailing list (as the sending address may be his foo@gmail.com). Would be great to somehow allow the mail-alternative to post to the mailing list as well...?

**Comment by leomelzer** [comment]
@sebastian-leidig You see any problems by requiring the email address to be unique upon sign up? This is somewhat required for #33

**Comment by sleidig** [comment]
No, that makes sense. Otherwise we are implicitly overwriting the other CiviCRM contact also.

Maybe return NULL from the API in that case?

I'll add an validation on the form for the sogintegration also.

**Comment by faboschert** [comment]
Having in mind that our original intention was to implement a model like
dashboard-----r/w----->LDAP<-----r-----Web_services and not
dashboard-----r/w----->(LDAP+Web_services) I'd prefer a cronjob for
synchronizing as long as it's not possible for us to let the web services
synchronize everything themselves. If we let the dashboard access the
specific databases, ldap would become useless somehow.

**Comment by leomelzer** [comment]
True that. But whats the implementation? 

A cronjob which runs every 5 minutes...
1. Check `ou=inactive`
2. Loop over all entries
3. execute create_sieve_forwardings.sh if no appropriate rule (file) was found

**Comment by leomelzer** [comment]
@sebastian-leidig Can CiviCRM sync the email from LDAP?

**Comment by sleidig** [comment]
For updating the "mail-alternative" field in LDAP, we agreed to the following solution in our Mumble:
1. Dashboard links to the CiviCRM Profile, where users can update all their personal information http://civicrm.laufen-ohne-grenzen.de/user
2. CiviCRM will get a custom extension to hook into profile changes and accordingly update LDAP alternative-mail

**Comment by sleidig** [comment]
Concerning the creation of sieve rules during createUser:

For a separate cronjob there is need to implement LDAP connection, search, etc.
How about directly calling a shell script to create the necessary file (e.g. the one here: /home/sebastian/mail_migration/create_sieve_forwardings.sh ) from PHP during createUser?

**Comment by leomelzer** [comment]
You're right, calling the script is probably a somewhat good way to do this. I'll adapt your script, move it to the dashboard project and sanitize the variables passed to it. Let's see how that goes.

As for the mail address, we should use a deep link to /user/5/edit/name_and_address because on the regular /user page it is not possible to change the mail address (it simply shows the `@studieren-ohne-grenzen.org` address with a note that it can't be changed).

**Comment by leomelzer** [comment]
1. Added a link in the profile data to CiviCRM for updating basic personal data
2. Opened an issue https://github.com/studieren-ohne-grenzen/sogintegration/issues/2 to update the LDAP mail field via the dashboard API whenever the user submits this CiviCRM form
3. Opened a separate issue for setting up the sieve rule, see #48 

Closing this now. Thanks for the help @sebastian-leidig

**Comment by sleidig** [comment]
Unfortunately the link to the CiviCRM Profile won't work that way.

Currently the link is `civicrm.studieren-ohne-grenzen.org/user/5/edit/name_and_address`
However, the `5` is a hard coded user id of a fixed drupal user. 
This is why I was suggesting `civicrm.laufen-ohne-grenzen.de/user` which links to the logged in user profile. Unfortunately the detailed URL like `civicrm.studieren-ohne-grenzen.org/user/edit/name_and_address` is not defined ...

Workaround for now could be to describe next to the link, where the user has to click and edit.
Or/Later implement something that solves this.

Also, we currently have an issue with matching CiviCRM Drupal accounts and the actual CiviCRM Contacts. But this is not related to the dashboard, so I am just mentioning this here.

**Comment by leomelzer** [comment]
I changed the link to the `/user` route and added a note. Maybe we figure out how to configure a nice route to deeplink to `name_and_address`, but I think it's fine this way.
