### ISSUE TITLE
Error when using API: Class 'SOG\Dashboard\this' not found

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#44]
When trying to use the api as in the demo https://github.com/studieren-ohne-grenzen/dashboard/blob/develop/app/sog/Tests/api.php  I get an error

`Fatal error: Class 'SOG\Dashboard\this' not found in /var/www/dashboard/app/sog/Dashboard/LdapAdapter.php on line 295`

The mentioned line reads
`if(this::attributeHasValue($entry, 'pending', $dnOfUser)) {`
Shouldn't this rather be `$this` or `self::`?

I am using the api from outside the dashboard folder however, so maybe rather this is causing the issues. (try the api.php under /var/www/)

**Comment by faboschert** [comment]
@sebastian-leidig Actually the class itself wasn't meant at all. I guess, I messed this up when resetting a git commitment.

**Comment by faboschert** [comment]
However, it should work now, hopefully.

**Comment by sleidig** [comment]
Great, works for me now. Thanks!
