### ISSUE TITLE
API createUser: LDAP field mailAlias

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#45]
The Mitgliederformular <> Dashboard API integration is working now. However, there are some minor polishings to be done:

`mailAlias` should contain the short-domain SOG email id, e.g. "foo@s-o-g.org" but is currently set to the personal mail, sam as `mail-alternative` by the API.

**Comment by leomelzer** [comment]
<img width="608" alt="screen shot 2015-08-14 at 18 52 49" src="https://cloud.githubusercontent.com/assets/23313/9279149/bb7b3ad2-42b5-11e5-8db4-7d088fc84e84.png">
