### ISSUE TITLE
Change $config

### ISSUE THREAD

**Issue by kehrwoche** [studieren-ohne-grenzen/dashboard#47]
When having to include config.php when using the API $config is probably not the best name and might override other vars in the context. Might be useful to change to $dashboardConfig or something similar.

**Comment by leomelzer** [comment]
@sebastian-leidig I'll change the value in the sog-integration module as well and publish it later.
@kehrwoche You might have to change this as well, your code isn't on GitHub yet, right?

This is hopefully the last concerning the API package.

**Comment by kehrwoche** [comment]
Thanks - yes I will have to change this, too.
Code will be uploaded to github within the next hours.
