### ISSUE TITLE
Setup sieve rule when creating a new user account

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#48]
See #39

**Comment by leomelzer** [comment]
@sebastian-leidig Just realized chown and putting stuff in that directory `/srv/vmail` requires root...calling a root shell from php...? :(

@kehrwoche Do you have a good idea on how to solve this? We want to create a sieve rule for newly signed up users, we need to create a file in a specific directory. See `/home/sebastian/mail_migration/create_sieve_forwardings.sh`

**Comment by sleidig** [comment]
I know, doesn't sound like a good idea ...
On the other hand, if we escape all parameters in the shell script properly and only take the two mail addresses from php there shouldn't be any possible security risk.

Would it be more safe to run a root level cronjob that takes data from LDAP? In the end it comes down to proper filtering of user inputs either way, doesn't it?

**Comment by leomelzer** [comment]
I tried implementing the shell script. I set up `www-data` in `/etc/sudoers` like this

```
www-data ALL=NOPASSWD: /path/to/create_sieve_forwarding.sh
```

This should only allow this one script to be executed as root.

@sebastian-leidig [`escapeshellarg`](http://ca3.php.net/manual/en/function.escapeshellarg.php) should do the job, right?

Relevant discussions for reference:
- https://unix.stackexchange.com/questions/47132/execute-shell-script-from-php-as-root-user
- https://unix.stackexchange.com/questions/115054/php-shell-exec-permission-on-linux-ubuntu

**Comment by leomelzer** [comment]
I just checked, the rules get properly setup. 

tested with `su www-data -c "php api.php"` in the Tests directory.

@faboschert @sebastian-leidig @kehrwoche Maybe you can have a quick look concerning the security (passing args and setup in sudoers file). More eyes, less problems. Thanks.

**Comment by sleidig** [comment]
Looks good to me. `escapeshellarg` only makes the parameter passing to the shell script save. The argument could still possibly game the sieve script though? I don't think much harm can be done there, however, as the sieve rules only apply to the new user's own mail account. (Otherwise we could check in `create_sieve_forwarding.sh` if the parameters really are valid email ids)

**Comment by leomelzer** [comment]
Thanks for the brief review, I'll leave it as is for the time being then.
