### ISSUE TITLE
Add "guest" e-mails to groups (mailinglists)

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#49]
We have the option to add "guests" to our LDAP tree (ou=guests,ou=people,o=sog-de,dc=sog) in order to put people on a mailinglist who don't have an OpenAtrium account.

As a group admin I need to be able to add new "guests" to my group when managing the mailinglist.

Is this functionality implemented yet?

**Comment by leomelzer** [comment]
Good point. No, this isn't implemented yet. 

What objectClasses does a guest have? 
Do we consider this a blocker to our migration?

**Comment by sleidig** [comment]
As we are (currently) only using them for storing the email id, inetOrgPerson should do as objectClass.

I wouldn't rate this as a blocker (after all, the IT team could do this manually in reasonable time). But it should be done soon (and maybe added a note to the FAQ for the time being).

**Comment by leomelzer** [comment]
OK, I'll add this to the Next milestone then. 

Implementation notes: 
1. simple email-input below list of users on "manage members" page
2. add new node to `ou=guests,o=sog-de,dc=sog` if one with the given email doesn't exist
3. add DN to the groupOfNames field for the given ou

**Comment by leomelzer** [comment]
Dennis and I just discussed this, we'll have to move this issue to the First Release milestone as it is somewhat crucial for the migration (cleaning up old memberships etc.). 

Also, think about how to deal with the lists in `ou=standalone-mailinglists,ou=groups,o=sog-de,dc=sog`

**Comment by leomelzer** [comment]
This is now implemented as of 3850f82a0ebfbecd7b833e519b9530fc4fc3e7db, there is a form below the manage members table.

I'll open a separate issue for the standalone mailing lists. 

See attached: 
![screen shot 2015-08-27 at 15 06 39](https://cloud.githubusercontent.com/assets/23313/9521161/67519fce-4ccd-11e5-9c7a-93d2e1b8d1d4.png)
