### ISSUE TITLE
Show the LDAP data

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#5]
**Account management section:** The user data (name, email,...).

Personal account page for the logged in user:
- [x] Change Password, see #7 
- [x] Setup Mail Alternative: see #12 

**Group management section:** A list of the groups owned by the user and a table containing a subset of users based on the current filter.

**Comment by leomelzer** [comment]
To update the password, call

``` php
$app['ldap']->updatePassword($myDn, 'old_password', 'new_password')
```

We should enforce some minimal requirements (e.g. validation) on the password. cc @kehrwoche 
I think >= 8 characters and >= 2 character classes [e.g. alpha + numeric] would be a minimum. What do you think?

**Comment by faboschert** [comment]
Everything is shown properly now. The buttons and fields to change the values do exist.
Now we need to make the values editable, see #6 #7 #8 #12

**Comment by leomelzer** [comment]
Works well for me! Cool.
