### ISSUE TITLE
Usability Improvements

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#52]
Some small suggestions for ease of use. These may not be entirely necessary.
- [x] _Meine Benutzerdaten_: Link the label "Gruppen" to the site where groups can be edited
- [x] On failed login (or maybe everywhere in the footer?) maybe put the IT mail address for questions and problems
- [x] Explain how a user can get admin rights for a group (in "Hilfe" and maybe in the descriptions on the "Gruppen" site?)
- [ ] ~~Change messagebox buttons for security questions from `OK`/`Cancel` to `Yes`/`No`?~~

**Comment by leomelzer** [comment]
Implementing the last suggestion requires adding a dependency to some modal dialog script, such as https://jqueryui.com/dialog/#modal-confirmation
We use the standard Javascript `alert()` where button labels can't be changed.

**Comment by leomelzer** [comment]
See 167510f3129979e4d15c433dab1deac72bf85698
