### ISSUE TITLE
Adding guest to group does nothing

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#53]
Adding a guest to a group as group admin through the dashboard gives a generic success message "... Gast hinzugefügt ..." but the name/mail is not displayed in the group afterwards and cannot be found in LDAP either.

**Comment by leomelzer** [comment]
@sebastian-leidig You mind checking again? Should work now. I'll deploy in a moment. Thanks for the report!

**Comment by sleidig** [comment]
Great, seems to work now.
Thanks!
