### ISSUE TITLE
Mail notifications to coordinators don't work

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#55]
Registration of a new member and request to join a group do not seem to cause any e-mails to the group admins (or the group mail account, e.g. "karlsruhe@studieren-ohne-grenzen.org").

**Comment by leomelzer** [comment]
Good catch. Two types:
1. For new members: Mail is sent to the group OU, so it'll try to send mails to lg_karlsruhe@studieren-ohne-grenzen.org which currently is not setup. There's no appropriate field to infer the correct name of the mailbox...looking at our names we could try to
   1. Remove `lg_`, `ak_`, `ressort_` prefix if exists => `$modifiedOU`
   2. Then send mail to `$modifiedOU@studieren-ohne-grenzen.org` which should cover most cases
2. For group requests: No mail currently. I'll take care.

@sebastian-leidig Would the solution for 1 be something we could live with for the time being?

**Comment by leomelzer** [comment]
Implemented my suggestion in https://github.com/studieren-ohne-grenzen/dashboard/blob/55c26305a3169b2ea702e3252623095731fd8b27/app/sog/Dashboard/DataUtilityServiceProvider.php#L40

**Comment by sleidig** [comment]
(1) should work out. Alternatively we could send notifications to all group admins, possibly using the same methods as for (2).

**Comment by leomelzer** [comment]
I'm using the same method for both types now which involves the prefix-replacing as suggested. This should do for most cases. Emailing all owners of the group is the other possibility...maybe even the more effective one?

@kehrwoche @faboschert What do you think? Who should we email for new group requests? The generic karlsruhe@s-o-g.org, all assigned `owners`, ...?

**Comment by sleidig** [comment]
With this, some notifications for group requests will fail because the assumed mail id does not exist. Particularly for the groups that are only special mailinglists. So the admin route would be more generic.

**Comment by leomelzer** [comment]
True, might lead to some weird moments if group admin 1 acts on the mail
before group admin 2, and group admin 2 doesn't see the request anymore.
But then again this could happen with the generic lokalgruppe@s-o-g.org
account as well, as they tend to be shared/forwarded to multiple people.

So let's implement it the proper way. If anyone is up for this, please
go ahead. Otherwise I'll take care tomorrow.

On 01/09/15 13:47, Sebastian wrote:

> With this, some notifications for group requests will fail because the
> assumed mail id does not exist. Particularly for the groups that are
> only special mailinglists. So the admin route would be more generic.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/studieren-ohne-grenzen/dashboard/issues/55#issuecomment-136685435.

## 

Leonhard Melzer
Etudes Sans Frontières - Studieren Ohne Grenzen Deutschland e.V.
IT-Team
leonhard.melzer@studieren-ohne-grenzen.org
www.studieren-ohne-grenzen.org

BILDUNG FÖRDERN - SELBSTHILFE ERMÖGLICHEN

**Comment by leomelzer** [comment]
I'll move this to a new issue also, as the bug itself is fixed.

**Comment by sleidig** [comment]
Thanks!

@leomelzer 
Is the link in the group request notification hard coded? If it is, don't forget to updated before migration (or already change it now).

> im Dashboard unter 'Neue Anfragen' http://dashboard.laufen-ohne-grenzen.de/members/meine-Gruppen

**Comment by leomelzer** [comment]
No, it's dynamic, the UrlGenerator in Silex is asked to return the full url with host and protocol and determines it on-the-fly. See https://github.com/studieren-ohne-grenzen/dashboard/blob/d1bd9ca84cce2d77086b7e54a10ecf50d71bf1e1/public/index.php#L98

**Comment by leomelzer** [comment]
Just checked, there are no hardcoded paths to fix in the dashboard project.
