### ISSUE TITLE
Improve the UI for filtering group members

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#60]
The checkboxes for filtering are easy to overlook and not always intuitive in their use.

**"Meine Gruppen"**
- Filter-Checkbox "Mitgliedschaften"/"Anfragen" nicht unbedingt intuitiv. Selbst ich habe erst auf zweiten Anlauf - als ich mich gefragt habe, was diese bedeuten - ihre Funktion erkannt. Habe aber davor schon vergeblich gesucht, wie ich nur meine aktiven Mitgliedschaften sehen kann.
- Maybe buttons would be more prominent?

**"Mitglieder Verwalten"**
- Checkbox "Meine Gruppe" wrongly named? Should this rather be "bestehende Mitglieder" or something like that?
- Rename "Neue Mitglieder" -> "Neue Anfragen"?
- Listing all users when both checkboxes are unchecked is rather confusing.
  - popup to add new users to the group would be clearer (list = aktuelle/angefrage Gruppenmitglieder; popup = other users to be added)
  - an easier improvement could be a third filter checkbox for all "Nicht-Gruppen Mitglieder" (or something like that)

**Comment by leomelzer** [comment]
I agree this is confusing. I'm thinking about switching the control to radio-inputs and adding an "Alle" option, changing the other texts to "Meine Mitgliedschaften" and "Meine Anfragen" 

Having multiple filter options (aka checkboxes) feels a bit like a poweruser feature and set theory is not necessarily everyones' favorite :)

@faboschert how do you feel about this?

**Comment by faboschert** [comment]
Yeah, Sebastian is right - it's not very intuitive.. If we decide for
radiobuttons, filters won't be necessary anymore and we could also use e.g.
multiple lists instead.
Maybe we could make the radiobuttons look like tabs for better visibility.
Alternative: Use checkboxes looking like a (crossed) eye (see:
http://fontello.com/#search=eye ).

**Comment by leomelzer** [comment]
I reworked it to the input type radio and made it behave like tabs. I think the UI is rather clear now, also with some minor adjustments to the labels:

# Manage Groups

<img width="1017" alt="screen shot 2015-09-01 at 10 16 30" src="https://cloud.githubusercontent.com/assets/23313/9599245/8e7c2664-5092-11e5-934e-a17897cad36b.png">

# Manage Members

<img width="1028" alt="screen shot 2015-09-01 at 10 20 36" src="https://cloud.githubusercontent.com/assets/23313/9599316/32f67884-5093-11e5-8bd1-f274558e9274.png">

What do you think? I'll deploy in a moment.

**Comment by sleidig** [comment]
Great, I think this is much easier to grasp now. Thanks!

It still might be overlooked. Maybe switch the filter radios with the search box to the left? Tab-style would be even better but this certainly is not a blocker

**Comment by leomelzer** [comment]
# Swapped fieldsets

<img width="1006" alt="screen shot 2015-09-01 at 14 07 26" src="https://cloud.githubusercontent.com/assets/23313/9603711/dc463400-50b2-11e5-9fee-7a8086d51b9e.png">

I think that's a good idea, I'll swap the fieldsets and then close the issue.
