### ISSUE TITLE
Feature: Change user password

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#7]
The user should be able to change the password.
- [x] Method in LdapAdapter
- [x] Method to handle the received data from the Browser
- [x] html-form

**Comment by leomelzer** [comment]
Depends on #11

**Comment by leomelzer** [comment]
This is now working. Currently the dashboard LDAP user has no write access to the password attribute, which I think is nice. But how do we deal with requests to reset an unknown password? No other App (e.g. OA) can handle this, right? Then we would need to grant further rights to the user.

@sebastian-leidig @kehrwoche Do we already have some mechanism for dealing with "forgotten passwords"?

**Comment by leomelzer** [comment]
We are going to validate passwords against:
1. minimum 8 character
2. minimum 1 letter and 1 number

**Comment by sleidig** [comment]
No, I haven't dealt with password recovery in the new systems. I'll only set a random initial password to new LDAP users on signup in the _sogintegration_ module.

**Comment by leomelzer** [comment]
@sebastian-leidig OK, so this would also be a responsibility of the dashboard then, right? We don't believe OwnCloud or any other system deals with that. Writing password fields in the LDAP tree is not possible by default (except by the user him/herself). 

For the time being (e.g. on launch) the reset will be possible via LAM, we'll discuss the reset feature in the next mumble.

**Comment by faboschert** [comment]
@leomelzer Changing the password works now. The password is also checked against an appropriate regex expression. However there is the option of using http://silex.sensiolabs.org/doc/providers/validator.html and/or http://silex.sensiolabs.org/doc/providers/form.html instead of the current solution, though I don't know yet how to implement this exactly. I just found this in the Silex documentation and wanted to register it.

**Comment by leomelzer** [comment]
Cool, thanks for adding the check! I'd say we leave it like this, if anything refactor it at some point to a private `validatePassword` method. Adding the mentioned validators would require another (or two other) dependency from Symfony. We fortunately don't have to deal with many user inputs anyways, so I guess this does the job. Closing this for now!
