### ISSUE TITLE
Feature: (Un-)lock users for a group

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#8]
The group owner should be able to lock or unlock users for the currently selected group.
- (un-)lock new members: move member from inactive to active in ldap
- (un-)lock members candidating for group membership: move entries from a field 'candidates' to the field 'members'

**Comment by leomelzer** [comment]
This will be discussed in the next Mumble.

**Comment by kehrwoche** [comment]
Especially we should discuss the behaviour of OA in this context

**Comment by leomelzer** [comment]
@kehrwoche This is now implemented in the API branch which will soon be merged into `develop`. Currently the `pending` attributes for the OUs are still missing, right? 

See https://github.com/studieren-ohne-grenzen/dashboard/blob/api/app/sog/Dashboard/LdapAdapter.php#L284-L299

**Comment by faboschert** [comment]
This is implemented now. If a user requests a membership for a group, a button to ignore the request (next to the button for adding the user) will be shown to the group admin.

However there is an ugly workaroud for a bug that has occured: When setting the default filters for listjs it seems like the list isn't fully put up. I "fixed" this by adding a delay time... (1.5 sec) :hourglass_flowing_sand: :joy:

**Comment by leomelzer** [comment]
Implemented as of af463aacf92d2ddb7aaf59ff423ccbca82610739
